CREATE VIEW application_with_history AS
SELECT curr.*, 
COALESCE(TOT_PREV_APP, 0) TOT_PREV_APP,
COALESCE(PREV_APPROVED_CNT, 0) PREV_APPROVED_CNT,
COALESCE(PREV_CANCELLED_CNT, 0) PREV_CANCELLED_CNT,
COALESCE(PREV_REFUSED_CNT, 0) PREV_REFUSED_CNT,
COALESCE(PREV_UNUSED_CNT, 0) PREV_UNUSED_CNT
FROM ln_application_data curr
LEFT OUTER JOIN prev_app_summary prev
ON curr.SK_ID_CURR = prev.PREV_SK_ID_CURR;
