CREATE VIEW prev_app_summary as
    SELECT 
        SK_ID_CURR AS PREV_SK_ID_CURR,
        COUNT(DISTINCT SK_ID_PREV) AS TOT_PREV_APP,
        SUM(CASE WHEN NAME_CONTRACT_STATUS = 'Approved' THEN 1 ELSE 0 END) AS PREV_APPROVED_CNT,
        SUM(CASE WHEN NAME_CONTRACT_STATUS = 'Canceled' THEN 1 ELSE 0 END) AS PREV_CANCELLED_CNT,
        SUM(CASE WHEN NAME_CONTRACT_STATUS = 'Refused' THEN 1 ELSE 0 END) AS PREV_REFUSED_CNT,
        SUM(CASE WHEN NAME_CONTRACT_STATUS = 'Unused offer' THEN 1 ELSE 0 END) AS PREV_UNUSED_CNT
    FROM previous_application
    WHERE SK_ID_CURR IN (SELECT SK_ID_CURR FROM ln_application_data)
    GROUP BY SK_ID_CURR

